smtp:
  :address: yourmailserver.org
  :port: 25
  :user_name: author
  :password: pass
  :authentication: :plain
  :enable_starttls_auto: true
notification_address: willgetmailtothisadress
 saraswati:
  couch_url: legacysystem
